// <auto-generated />
using System;
using Andy.CodeIndex.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;

#nullable disable

namespace Andy.CodeIndex.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CodeIndexDbContext))]
    [Migration("20260320172945_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("HeadCommitSha")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "Name")
                        .IsUnique();

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.ChunkLineRange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EndLine")
                        .HasColumnType("integer");

                    b.Property<Guid>("EnrichmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("StartLine")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnrichmentId");

                    b.ToTable("ChunkLineRanges");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.Commit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AuthorName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CommittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<bool>("IsIndexed")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("CommittedAt");

                    b.HasIndex("Sha");

                    b.HasIndex("RepositoryId", "Sha")
                        .IsUnique();

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.ContentEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Vector>("EmbeddingVector")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.Property<Guid>("EnrichmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("IndexType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("EmbeddingVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("EmbeddingVector"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("EmbeddingVector"), new[] { "vector_cosine_ops" });

                    b.HasIndex("EnrichmentId");

                    b.HasIndex("IndexType");

                    b.ToTable("ContentEmbeddings");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.Enrichment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int?>("EndLine")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Language")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasComputedColumnSql("to_tsvector('english', coalesce(\"Content\", ''))", true);

                    b.Property<int?>("StartLine")
                        .HasColumnType("integer");

                    b.Property<string>("Subtype")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CommitId");

                    b.HasIndex("FilePath");

                    b.HasIndex("Language");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("Type", "Subtype");

                    b.ToTable("Enrichments");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.IndexingTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChainId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ChainId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "Priority", "CreatedAt");

                    b.ToTable("IndexingTasks");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CloneUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("DefaultBranch")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastIndexedCommitSha")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PersonalAccessToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.RepositoryFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Language")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Language");

                    b.HasIndex("CommitId", "Path")
                        .IsUnique();

                    b.ToTable("RepositoryFiles");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.Branch", b =>
                {
                    b.HasOne("Andy.CodeIndex.Domain.Entities.Repository", "Repository")
                        .WithMany("Branches")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.ChunkLineRange", b =>
                {
                    b.HasOne("Andy.CodeIndex.Domain.Entities.Enrichment", "Enrichment")
                        .WithMany("LineRanges")
                        .HasForeignKey("EnrichmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrichment");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.Commit", b =>
                {
                    b.HasOne("Andy.CodeIndex.Domain.Entities.Repository", "Repository")
                        .WithMany("Commits")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.ContentEmbedding", b =>
                {
                    b.HasOne("Andy.CodeIndex.Domain.Entities.Enrichment", "Enrichment")
                        .WithMany("Embeddings")
                        .HasForeignKey("EnrichmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrichment");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.Enrichment", b =>
                {
                    b.HasOne("Andy.CodeIndex.Domain.Entities.Commit", "Commit")
                        .WithMany("Enrichments")
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Andy.CodeIndex.Domain.Entities.Repository", "Repository")
                        .WithMany("Enrichments")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commit");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.IndexingTask", b =>
                {
                    b.HasOne("Andy.CodeIndex.Domain.Entities.Repository", "Repository")
                        .WithMany("IndexingTasks")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.RepositoryFile", b =>
                {
                    b.HasOne("Andy.CodeIndex.Domain.Entities.Commit", "Commit")
                        .WithMany("Files")
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commit");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Andy.CodeIndex.Domain.Entities.Repository", "Repository")
                        .WithMany("Tags")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.Commit", b =>
                {
                    b.Navigation("Enrichments");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.Enrichment", b =>
                {
                    b.Navigation("Embeddings");

                    b.Navigation("LineRanges");
                });

            modelBuilder.Entity("Andy.CodeIndex.Domain.Entities.Repository", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Commits");

                    b.Navigation("Enrichments");

                    b.Navigation("IndexingTasks");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
